security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
logging:
  level:
    io:
      pivotal: DEBUG
a
greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-qa.cfapps.io/quote